"""
Local test for LLM explanation layer.
Tests the explainer with sample data (no API key needed for fallback mode).
"""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / 'src'))

from llm import OfferExplainer, ExplanationOutput


def test_explainer_with_fallback():
    """Test explainer in fallback mode (no API key)."""
    
    # Sample offer from pricing engine
    sample_offer = {
        'template_id': 'T3_NIGHT',
        'template_name': 'Night & Cash Risk',
        'coverages': ['theft_extended', 'cash_on_premises', 'vandalism'],
        'plafond_tnd': 36000.0,
        'franchise_tnd': 2400,
        'prime_annuelle_tnd': 638.93,
        'breakdown': {
            'expected_cost': 2500.0,
            'expected_loss': 450.0,
            'expense_margin': 0.45,
            'feature_adjustment': 0.986,
            'multiplier': 1.6,
            'p_claim': 0.18,
            'uncertainty_buffer': 0.15
        },
        'decision_reasons': ['rule_open_at_night', 'rule_high_frequency'],
        'flags': {'high_risk': False, 'underwriting_review': False}
    }
    
    sample_profile = {
        'activity_type': 'Café',
        'governorate': 'Tunis',
        'shop_area_m2': 45,
        'assets_value_tnd': 40000,
        'open_at_night': True,
        'security_alarm': False,
        'security_camera': True,
        'fire_extinguisher': True
    }
    
    sample_ml = {
        'segment_name': 'Cluster 2 - Risque Élevé',
        'uncertainty_score': 'Élevé'
    }
    
    print("\n" + "="*70)
    print("🧪 TESTING LLM EXPLAINER - FALLBACK MODE (No API Key)")
    print("="*70)
    
    explainer = OfferExplainer(api_key=None)
    
    result = explainer.generate_explanations(
        offer=sample_offer,
        client_profile=sample_profile,
        ml_outputs=sample_ml
    )
    
    assert isinstance(result, ExplanationOutput)
    assert len(result.customer_explanation) > 0
    assert len(result.insurer_explanation) > 0
    assert len(result.recommendations) > 0
    assert result.disclaimer is not None
    
    print("\n✅ All assertions passed\n")
    print("📋 CUSTOMER EXPLANATION:")
    print("-" * 70)
    print(result.customer_explanation)
    
    print("\n🔍 INSURER EXPLANATION:")
    print("-" * 70)
    print(result.insurer_explanation)
    
    print("\n💡 RECOMMENDATIONS:")
    print("-" * 70)
    print(result.recommendations)
    
    print("\n⚠️ DISCLAIMER:")
    print("-" * 70)
    print(result.disclaimer)
    
    print("\n" + "="*70)
    print("✅ TEST COMPLETED SUCCESSFULLY")
    print("="*70 + "\n")


def test_explainer_with_api_key():
    """Test with real Gemini API (requires GOOGLE_API_KEY env var)."""
    
    import os
    
    api_key = os.getenv('GOOGLE_API_KEY')
    
    if not api_key:
        print("\n⚠️ GOOGLE_API_KEY not set - skipping real API test")
        print("To test with real LLM, set: export GOOGLE_API_KEY='your-key'\n")
        return
    
    print("\n" + "="*70)
    print("🧪 TESTING LLM EXPLAINER - REAL API MODE")
    print("="*70)
    
    sample_offer = {
        'template_id': 'T2_PLUS',
        'template_name': 'Commerce Plus',
        'coverages': ['fire', 'theft_extended', 'water_damage', 'equipment_breakdown'],
        'plafond_tnd': 80000.0,
        'franchise_tnd': 1500,
        'prime_annuelle_tnd': 1245.80,
        'breakdown': {
            'expected_cost': 3500.0,
            'expected_loss': 525.0,
            'expense_margin': 0.40,
            'feature_adjustment': 0.95,
            'multiplier': 1.45,
            'p_claim': 0.15,
            'uncertainty_buffer': 0.12
        },
        'decision_reasons': ['rule_high_assets', 'rule_pharmacy'],
        'flags': {'high_risk': False, 'underwriting_review': False}
    }
    
    sample_profile = {
        'activity_type': 'Pharmacie',
        'governorate': 'Sfax',
        'shop_area_m2': 65,
        'assets_value_tnd': 90000,
        'open_at_night': False,
        'security_alarm': True,
        'security_camera': True,
        'fire_extinguisher': True
    }
    
    sample_ml = {
        'segment_name': 'Cluster 1 - Risque Modéré',
        'uncertainty_score': 'Faible'
    }
    
    explainer = OfferExplainer(api_key=api_key, model="gemini-2.5-flash-lite")
    
    result = explainer.generate_explanations(
        offer=sample_offer,
        client_profile=sample_profile,
        ml_outputs=sample_ml
    )
    
    print("\n📋 CUSTOMER EXPLANATION (Generated by LLM):")
    print("-" * 70)
    print(result.customer_explanation)
    
    print("\n🔍 INSURER EXPLANATION (Generated by LLM):")
    print("-" * 70)
    print(result.insurer_explanation)
    
    print("\n💡 RECOMMENDATIONS (Generated by LLM):")
    print("-" * 70)
    print(result.recommendations)
    
    print("\n" + "="*70)
    print("✅ REAL API TEST COMPLETED")
    print("="*70 + "\n")


if __name__ == "__main__":
    # Test 1: Fallback mode (always works)
    test_explainer_with_fallback()
    
    # Test 2: Real API (requires env var)
    test_explainer_with_api_key()